// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Entity.Models;

public partial class nEdit_DEVContext : DbContext
{
    public nEdit_DEVContext(DbContextOptions<nEdit_DEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblLogin> TblLogins { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblLogin>(entity =>
        {
            entity.HasKey(e => e.LoginId).HasName("PK__tbl_logi__C2C971DB76A9AA19");

            entity.ToTable("tbl_login");

            entity.Property(e => e.LoginId).HasColumnName("login_id");
            entity.Property(e => e.LoginName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("login_name");
            entity.Property(e => e.LoginPass)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("login_pass");
            entity.Property(e => e.LoginStatus).HasColumnName("login_status");
            entity.Property(e => e.RetryCount)
                .HasDefaultValueSql("((0))")
                .HasColumnName("retry_count");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}