// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class TblLogin
{
    public int LoginId { get; set; }

    public string LoginName { get; set; }

    public string LoginPass { get; set; }

    public byte? LoginStatus { get; set; }

    public int? RetryCount { get; set; }
}